name: Init

on: [push]


jobs:
  init:
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: sudo apt install unzip axel
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 16
      - name: Setup JavaFX
        run: |
          cd /tmp
          axel -n 8 https://download2.gluonhq.com/openjfx/17/openjfx-17-ea+11_linux-x64_bin-sdk.zip
          unzip /tmp/openjfx-17-ea+11_linux-x64_bin-sdk.zip -d /tmp
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - name: Saving build-date
        run: |
          cd src/main/resources/com/stream_pi/client
          echo $(date +'%d-%m-%Y %H:%M:%S %Z') > build-date
          echo $(date +'%d-%m-%Y %H:%M:%S %Z')
          ls
          cat build-date
      - name: Build Jars
        run: |
          mvn -X package
      - name: Save built jars
        uses: actions/upload-artifact@v2
        with:
          name: built-jars
          path: target/lib/*
      - name: Set Version
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Calculate required modules
        run: |
          JDEPS_MODULES=$(jdeps --module-path $JAVAFX_SDK/:target/lib/ --print-module-deps --ignore-missing-deps target/lib/client-$VERSION.jar)
          JAVAFX_MODULES=javafx.fxml,javafx.media,javafx.swing,javafx.web
          echo "REQ_MODULES=$JDEPS_MODULES,$JAVAFX_MODULES" >> $GITHUB_ENV
        env:
          JAVAFX_SDK: /tmp/javafx-sdk-17/lib/
      - name: Saving REQ_MODULES
        run: |
          echo $REQ_MODULES > req_modules.txt
      - name: Uploading REQ_MODULES
        uses: actions/upload-artifact@v2
        with:
          name: req_modules
          path: req_modules.txt
      - name: Saving VERSION
        run: |
          echo $VERSION > version.txt
      - name: Uploading VERSION
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
