name: Build Linux
on:
  workflow_run:
    workflows: ["Build Essential Actions"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: sudo apt install xdg-utils libc6 xdg-utils zlib1g libpng16-16 libasound2 libbsd-dev zip libblkid1 libdbus-1-3 libexpat1 libgpg-error0 liblzma5 libmount1 libpcre3 libselinux1 libsystemd0 libuuid1
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 16
      - name: Setup JavaFX
        run: |
          wget -P /tmp https://download2.gluonhq.com/openjfx/17/openjfx-17-ea+11_linux-x64_bin-jmods.zip
          unzip /tmp/openjfx-17-ea+11_linux-x64_bin-jmods.zip -d /tmp
      - name: Download built jars
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: built-jars
          path: target/lib/
      - name: Download REQ_MODULES
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: req_modules
      - name: Download VERSION
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: version
      - name: Add VERSION to environment
        run: |
          echo "VERSION=$(<version.txt)" >> $GITHUB_ENV
      - name: Add REQ_MODULES to environment
        run: |
          echo "REQ_MODULES=$(<req_modules.txt)" >> $GITHUB_ENV
      - name: Create Bundle using JPackage
        run: |
          # Create DEB
          .github/scripts/jpackage.sh \
          --icon assets/linux-icon.png \
          --app-version ${{ env.VERSION }} \
          --linux-menu-group "Stream-Pi" \
          --license-file LICENSE.txt \
          --type deb

          # Create App Image
          .github/scripts/jpackage.sh \
          --icon assets/linux-icon.png \
          --app-version ${{ env.VERSION }} \
          --type app-image

          cd $INSTALL_DIR
          mv *.deb stream-pi-client-linux-x64-${{ env.VERSION }}-debian.deb
          mv 'Stream-Pi Client' stream-pi-client-${{ env.VERSION }}
          zip -r stream-pi-client-linux-x64-${{ env.VERSION }}-executable.zip stream-pi-client-${{ env.VERSION }}
          rm -r stream-pi-client-${{ env.VERSION }}
        env:
          MAIN_CLASS: com.stream_pi.client.Main
          JAVAFX_JMODS: /tmp/javafx-jmods-17/
          JPACKAGE_HOME: ${{ env.JAVA_HOME }}
          INSTALL_DIR: target/install
      - name: Saving Linux x64 DEB
        uses: actions/upload-artifact@v2
        with:
          name: linux-deb
          path: target/install/stream-pi-client-linux-x64-${{ env.VERSION }}-debian.deb
      - name: Saving Linux x64 ZIP
        uses: actions/upload-artifact@v2
        with:
          name: linux-zip
          path: target/install/stream-pi-client-linux-x64-${{ env.VERSION }}-executable.zip

