name: Build MacOS
on:
  workflow_run:
    workflows: ["Build Linux"]
    types:
      - completed

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 16
      - name: Setup JavaFX
        run: |
          wget -P /tmp https://download2.gluonhq.com/openjfx/17/openjfx-17-ea+11_linux-x64_bin-jmods.zip
          unzip /tmp/openjfx-17-ea+11_linux-x64_bin-jmods.zip -d /tmp
      - name: Download built jars
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: built-jars
          path: target/lib/
      - name: Download REQ_MODULES
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: req_modules
      - name: Download VERSION
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: version
      - name: Add VERSION to environment
        run: |
          echo "VERSION=$(<version.txt)" >> $GITHUB_ENV
      - name: Add REQ_MODULES to environment
        run: |
          echo "REQ_MODULES=$(<req_modules.txt)" >> $GITHUB_ENV
      - name: Create Bundle using JPackage
        run: |
          # Create DMG
          .github/scripts/jpackage.sh \
          --icon assets/macos-icon.icns \
          --license-file LICENSE.txt \
          --type dmg

          cd $INSTALL_DIR
          mv *.dmg stream-pi-client-macos-x64-${{ env.VERSION }}.dmg
        env:
          MAIN_CLASS: com.stream_pi.client.Main
          JAVAFX_JMODS: /tmp/javafx-jmods-17/
          JPACKAGE_HOME: ${{ env.JAVA_HOME }}
          INSTALL_DIR: target/install
      - name: Saving MacOS x64 DMG
        uses: actions/upload-artifact@v2
        with:
          name: macos-dmg
          path: target/install/stream-pi-client-macos-x64-${{ env.VERSION }}.dmg

