name: Build Windows
on:
  workflow_run:
    workflows: ["Build MacOS"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 16
      - name: Download REQ_MODULES
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: req_modules
      - name: Download VERSION
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: version
      - name: Setup JavaFX
        run: |
          bitsadmin /Transfer DownsdfloadJavaFX https://download2.gluonhq.com/openjfx/17/openjfx-17-ea+11_linux-x64_bin-jmods.zip D:\openjfx-17-ea+11_linux-x64_bin-jmods.zip
          Expand-Archive -Force D:\openjfx-17-ea+11_linux-x64_bin-jmods.zip D:\
      - name: Download built jars
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: init.yml
          name: built-jars
          path: target/lib/
      - name: Create Bundle using JPackage
        id: project
        shell: cmd
        run: |
          call .github\scripts\jpackage.bat
        env:
          MAIN_CLASS: com.stream_pi.client.Main
          JAVAFX_JMODS: D:\javafx-jmods-17\
          JPACKAGE_HOME: ${{ env.JAVA_HOME }}
          INSTALL_DIR: target/install
      - name: Saving Windows x64 EXE
        uses: actions/upload-artifact@v2
        with:
          name: windows-exe
          path: target/install/*.exe

